apiVersion: 1

datasources:
  - name: k6influxdb
    type: influxdb
    access: proxy
    database: k6
    url: http://influxdb:8086
    isDefault: true

# datasources:
#   - name: InfluxDB_v2_Flux
#     type: influxdb
#     access: proxy
#     url: http://influxdb:8086
    # jsonData:
    #   # This database should be mapped to a bucket
    #   dbName: k6
    #   httpMode: GET
    #   httpHeaderName1: 'Authorization'
    # secureJsonData:
    #   httpHeaderValue1: 'Token my-super-secret-auth-token'


    # jsonData:
    #   version: Flux
    #   organization: my-org
    #   defaultBucket: my-bucket
    #   tlsSkipVerify: true
    # secureJsonData:
    #   token: my-super-secret-auth-token