networks:
  default:
    name: docker-default-network
    external: true

services:

  postgres:
    image: postgres-xa:14.1
    build:
      context: src/test/docker/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: customer
      POSTGRES_DB: customer
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 30s
      retries: 5
    mem_limit: 512m
    mem_reservation: 128m

  postgres-two:
    image: postgres-xa:14.1
    build:
      context: src/test/docker/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: logentry
      POSTGRES_DB: logentry
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 30s
      retries: 5
    mem_limit: 512m
    mem_reservation: 128m
