networks:
  default:
    name: docker-default-network
    external: true

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3003:8080"

    volumes:
      - open-webui:/app/backend/data
    restart: always

volumes:
  ollama:
  open-webui:
