---
openapi: 3.1.0
components:
  schemas:
    JsonValue:
      type: object
      properties:
        valueType:
          $ref: "#/components/schemas/ValueType"
    ValueType:
      type: string
      enum:
      - ARRAY
      - OBJECT
      - STRING
      - NUMBER
      - "TRUE"
      - "FALSE"
      - "NULL"
paths:
  /resourcewithmetrics:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                $ref: "#/components/schemas/JsonValue"
        required: true
      responses:
        "200":
          description: OK
      summary: Save Object From Json
      tags:
      - Resource With Metrics
  /resourcewithmetrics/classic:
    get:
      responses:
        "200":
          description: OK
      summary: Get All Classic
      tags:
      - Resource With Metrics
  /resourcewithmetrics/virtual:
    get:
      responses:
        "200":
          description: OK
      summary: Get All Virtual
      tags:
      - Resource With Metrics
  /resourcewithmetrics/{id}:
    get:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
      summary: Load
      tags:
      - Resource With Metrics
info:
  title: loadtesting API
  version: 1.0.0-SNAPSHOT
servers:
- url: http://localhost:8080
  description: Auto generated value
- url: http://0.0.0.0:8080
  description: Auto generated value
