---
openapi: 3.1.0
paths:
  /jsonresource:
    get:
      parameters:
      - name: surname
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: {}
      summary: Search
      tags:
      - Json Resource
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                $ref: "#/components/schemas/JsonValue"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: {}
        "400":
          description: Bad Request
      summary: Save Object From Json
      tags:
      - Json Resource
  /jsonresource/{id}:
    get:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: {}
      summary: Load
      tags:
      - Json Resource
components:
  schemas:
    JsonValue:
      type: object
      properties:
        valueType:
          $ref: "#/components/schemas/ValueType"
    ValueType:
      type: string
      enum:
      - ARRAY
      - OBJECT
      - STRING
      - NUMBER
      - "TRUE"
      - "FALSE"
      - "NULL"
info:
  title: json-sql-postgres API
  version: 1.0.0-SNAPSHOT
servers:
- url: http://localhost:8080
  description: Auto generated value
- url: http://0.0.0.0:8080
  description: Auto generated value
